default_platform(:android)

platform :android do
  desc "Build Android App"
  lane :build_android do
    gradle(
      task: "assembleDebug",
      project_dir: ".",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
      }
    )
  end
end
